#  Utiliser une image Node.js
FROM node:16

# Étape 2: Créer un repertoire de travail
WORKDIR /app

# Étape 3: Copier les fichiers package.json et package-lock.json dans le répertoire de travail
COPY package*.json ./

# Étape 4: Installer les dépendances du projet
RUN npm install

# Étape 5: Copier tout le reste du code dans le répertoire de travail
COPY . .

# Étape 6: Exposer le port 5000 pour accéder à l'application
EXPOSE 5000

# Étape 7: Lancer l'application
CMD ["npm", "start"]